# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 16:03
from __future__ import unicode_literals

import app.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='category_icon', verbose_name='Иконка категории')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название коллекции')),
                ('description', models.CharField(max_length=250, verbose_name='Описание коллекции')),
                ('image', models.ImageField(upload_to='', verbose_name='Общее фото коллекции')),
                ('data_create', models.DateField(verbose_name='Дата создания коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция одежды',
                'verbose_name_plural': 'Коллекции одежды',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Галерея товара',
                'verbose_name_plural': 'Галерея товаров',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('color', app.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет обложки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Collection', verbose_name='Из коллекции')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Gallery', verbose_name='Изображения товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Thing'),
        ),
    ]
