# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190301_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('rus', models.PositiveIntegerField(verbose_name='Русский размер')),
                ('all', models.CharField(max_length=7, verbose_name='Международный размер')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='app.Thing')),
            ],
        ),
    ]
