# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190304_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thing',
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Название фотки'),
        ),
    ]
