# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190304_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Thing'),
            preserve_default=False,
        ),
    ]
