# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gallery_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='thing',
            name='date_add',
            field=models.DateField(auto_now=True, verbose_name='Дата добавления'),
        ),
    ]
