# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190305_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app.Color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='app.Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='thing',
            name='color',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='size',
        ),
        migrations.AddField(
            model_name='relationship',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='app.Thing'),
        ),
    ]
